services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  emitter:
    build: backend
    depends_on:
      - redis
  server:
    build: server
    depends_on:
      - redis
  client:
    build: client
    deploy:
      replicas: 3
    depends_on:
      - server
